spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://212.64.64.117:3306/mojito_note?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lfq12345

logging:
  level:
    root: info
    com.charles: debug
  file:
    name: logs/mojito-note.log
